apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-portfolio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "frontend-portfolio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend-portfolio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend-portfolio.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend-portfolio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 100m
