replicaCount: 1

image:
  repository: frontend-portfolio
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: ilhrf.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - ilhrf.org
      secretName: ilhrf-tls

env:
  - name: NEXT_PUBLIC_FRONTEND_URL
    value: "https://ilhrf.org"
  - name: NEXT_PUBLIC_CROWDSOURCING_URL
    value: "https://crowdsourcing.ilhrf.org"
